apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.uiIssuerNode.configMap.issuerApiUiName  }}
  labels:
    {{- include "polygon-id-issuer.staticLabel" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
data:
  ISSUER_API_UI_SERVER_URL: {{ .Values.appdomain }}
  ISSUER_UI_AUTH_PASSWORD: {{ .Values.uiIssuerNode.configMap.issuerUiAuthPassword }}
  ISSUER_UI_AUTH_USERNAME: {{ .Values.uiIssuerNode.configMap.issuerUiAuthUsername }}
  ISSUER_UI_BLOCK_EXPLORER_URL: {{ .Values.uiIssuerNode.configMap.issuerUiBlockExplorerUrl }}
  ISSUER_API_UI_AUTH_USER: {{ .Values.uiIssuerNode.configMap.issuerApiUiAuthUser }}
  ISSUER_API_UI_AUTH_PASSWORD: {{ .Values.uiIssuerNode.configMap.issuerApiUiAuthPassword }}
  ISSUER_API_UI_ISSUER_NAME: {{ .Values.uiIssuerNode.configMap.issuerApiUiIssuerName }}
  ISSUER_UI_IPFS_GATEWAY_URL: {{ .Values.uiIssuerNode.configMap.issuerUiIpfsGatewayUrl }}